name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install project + test deps
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest .
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests
      run: pytest

  build-wheel:
    needs: test 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install build backend
      run: python -m pip install --upgrade build

    - name: Build wheel
      run: python -m build --wheel --outdir dist

    - name: Upload wheel
      uses: actions/upload-artifact@v4
      with:
        name: decompilellm-${{ steps.date.outputs.date }}-${{ github.sha }}
        path: dist/*.whl
        retention-days: 14
